import type { Metadata } from 'next';

import ThemeRegistry from './components/theme-registry/ThemeRegistry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeRegistry>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ThemeRegistry>
  );
}
